/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ExtractNativeOptions {
  format?: string
  maxBytes?: number
}

export declare function extractText(input: Buffer, options?: ExtractNativeOptions | undefined | null): Promise<string>

export declare function extractTextFromPath(path: string, options?: ExtractNativeOptions | undefined | null): Promise<string>

export declare function parsePkPass(input: Buffer, options?: PkPassNativeOptions | undefined | null): Promise<PkPassResult | null>

export declare function parsePkPassFromPath(path: string, options?: PkPassNativeOptions | undefined | null): Promise<PkPassResult | null>

export interface PkPassNativeOptions {
  maxBytes?: number
}

export interface PkPassResult {
  pass: any
  localization?: string
  stripImage?: string
}

export declare function setInMemoryThresholdBytes(n: number): void

export declare function setMaxBytes(n: number): void

export declare function setMaxConcurrent(n: number): void

export declare function setMaxWorkingSetMB(n: number): void
